name: "Automatically release when new version of `expect` is released"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          git config --global user.name "`git --no-pager log -1 --format='%an'`"
          git config --global user.email `git --no-pager log -1 --format='%ae'`
      - run: |
          npm install
          npm install --save-dev expect@latest
          node auto-release.mjs `npm view expect version`
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
